### PR TITLE
xdjlib : Make it gradle

### PR DESCRIPTION
**Pull request by msfjarvis**
Builds fine http://hastebin.com/ulubeyetug.pas

### CODE REVIEW

**Comment by xdevs23** [comment]
Thanks but I already have the necessary files, clean and working.

**Comment by msfjarvis** [comment]
I was just bored this morning 😂

**Comment by xdevs23** [comment]
Nice :joy:

**Comment by xdevs23** [comment]
Don't worry, I'll surely get to do that.

**Pull request closed without merging**
